version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://xwswwqsq.duckdns.org:8080
    container_name: hobits-frontend
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - hobits-network

networks:
  hobits-network:
    driver: bridge
